const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {JSDOM,VirtualConsole}=require(process.env.PHY_JSDOM_PATH||'jsdom');
const errors=[],calls=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const id='a'.repeat(32),old='b'.repeat(32);
let deferred=null;
const data={inherited:true,sources:[{task_id:old,outcome:'passed'}],conditions:['mass 190 kg','new heating condition'],file_count:80,context_count:1,read_count:0,copied_count:1,unchanged_count:0,total:80,next_offset:50,plan:{new_work:['extend heat model']},files:[{file_id:'one',source_path:'node_12/model.py',source_task_id:old,bytes:100,historical_status:'accepted',usage:[{node_id:'node_1',action:'context_attached'},{node_id:'node_1',action:'copied'}]}]};
const job=()=>({id:old,state:'finished',query:'original',round:1,revision:0,task_dir:'old',capabilities:{},critic_settings:{accept_threshold:.85,redraft_threshold:.6,retrieval_threshold:.5,retrieval_enabled:false},messages:[],logs:[]});
const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../web/index.html'),'utf8'),{url:'http://127.0.0.1:8765',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.setInterval=()=>0;w.fetch=async url=>{calls.push(url);if(url.includes('/inheritance?')&&deferred)return deferred;return {ok:true,json:async()=>url==='/api/capabilities'?{defaults:{},options:[],critic_defaults:job().critic_settings}:url==='/api/tasks'?{tasks:[]}:url.includes('/inheritance?')?structuredClone(data):url.endsWith('/rounds')?{rounds:[]}:job()};};}});
const w=dom.window,d=w.document;
(async()=>{try{
 await new Promise(r=>setImmediate(r));w.eval('task="'+id+'"');w.renderInheritance(structuredClone(data),id);
 assert.match(d.getElementById('inheritanceHint').textContent,/完整继承 80.*工具读取 0/);
 assert.match(d.getElementById('inheritanceFiles').textContent,/旧条件下已验收/);
 assert.match(d.getElementById('inheritanceFiles').textContent,/提供到节点上下文/);
 assert.match(d.getElementById('inheritanceFiles').textContent,/复制到本轮节点/);
 assert.match(d.getElementById('inheritanceConditions').textContent,/mass 190 kg.*new heating condition/s);
 assert.match(d.getElementById('inheritanceConditions').textContent,/extend heat model/);
 assert.equal(d.querySelector('#inheritanceFiles a').getAttribute('href'),'/api/tasks/'+id+'/inherited-file?file_id=one');
 console.log('PASS: inherited history, original acceptance, context/copy/read distinctions and verified download link.');
 await w.refreshInheritance();d.getElementById('inheritanceNext').click();await new Promise(r=>setImmediate(r));assert.ok(calls.some(x=>x.includes('offset=50')));
 d.getElementById('inheritanceSearch').value='model.py';d.getElementById('inheritanceFind').click();await new Promise(r=>setImmediate(r));assert.ok(calls.some(x=>x.includes('offset=0&query=model.py')));
 console.log('PASS: inherited file pagination and search call the actual endpoint.');
 const malicious=structuredClone(data);malicious.files[0].source_path='<img src=x onerror=alert(1)>';malicious.files[0].usage[0].reason='<script>throw 1</script>';w.renderInheritance(malicious,id);
 assert.equal(d.querySelector('#inheritanceFiles img'),null);assert.equal(d.querySelector('#inheritanceFiles script'),null);
 console.log('PASS: old paths and usage reasons are rendered as escaped text.');
 w.eval('task="'+id+'"');let resolve;deferred=new Promise(r=>resolve=r);const pending=w.refreshInheritance();w.eval('task="'+old+'"');w.renderInheritance({inherited:false,sources:[],files:[],conditions:[],next_offset:null},old);resolve({ok:true,json:async()=>structuredClone(data)});await pending;deferred=null;
 assert.match(d.getElementById('inheritanceHint').textContent,/没有继承记录/);assert.equal(d.querySelectorAll('#inheritanceFiles tr').length,0);
 console.log('PASS: late inherited responses cannot leak across tasks.');
 assert.deepEqual(errors,[]);
}finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
